<a href="https://colab.research.google.com/github/yack97/Numpy/blob/main/practica_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
python_list = [1,2,3,6,8,9]
array=np.array(python_list)
print(array)

[1 2 3 6 8 9]


In [5]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
random_generator=np.random.RandomState(10)
random_generator.rand(3,3)

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [9]:
random_generator.randint(0,10,(3,3))

array([[8, 6, 4],
       [3, 0, 4],
       [6, 8, 1]])

Indexing - slicing

In [11]:
one_de_array=np.arange(10)
one_de_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
one_de_array[:5]

array([0, 1, 2, 3, 4])

In [13]:
one_de_array[::5]

array([0, 5])

In [14]:
one_de_array[1::5]

array([1, 6])

In [15]:
lista_indices = [1,2,-3]
one_de_array[lista_indices]

array([1, 2, 7])

In [16]:
randor_generator=np.random.RandomState(10)
two_de_array=randor_generator.randint(0,10,(3,4))
two_de_array

array([[9, 4, 0, 1],
       [9, 0, 1, 8],
       [9, 0, 8, 6]])

In [17]:
randor_generator_seed=np.random.default_rng(40)
randor_generator_seed.integers(0,10,(3,4))

array([[5, 7, 0, 6],
       [4, 9, 0, 0],
       [4, 6, 0, 9]])

In [19]:
randor_generator_seed=np.random.default_rng(40)


In [20]:
low=0
high=10
size=(3,4)
randor_generator_seed.integers(low,high,size)

array([[5, 7, 0, 6],
       [4, 9, 0, 0],
       [4, 6, 0, 9]])

In [21]:
low=0
high=10
size=(3,4)
randor_generator_seed.uniform(low,high,size)
two_de_array

array([[9, 4, 0, 1],
       [9, 0, 1, 8],
       [9, 0, 8, 6]])

In [22]:
two_de_array[2:,:]

array([[9, 0, 8, 6]])

Vectorizacion

In [24]:
a=np.array([0,3,5])
b=np.array([1,2,3])
a+b

array([1, 5, 8])

In [26]:
a=np.array([0,3,5])
b=5
a+b

array([ 5,  8, 10])

In [27]:
a=np.ones((3,3))
b=np.array([1,2,3])
a+b

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [30]:
a=np.array([[0],[1],[2]])

In [31]:
a

array([[0],
       [1],
       [2]])